In [2]:
import os
import re
import time
import random
import pickle
from collections import Counter

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix
from tqdm.auto import tqdm

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(42)
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {DEVICE}")

Device: cpu


/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
DATA_DIR = "liar2"          # folder containing train.csv, valid.csv, test.csv
TRAIN_CSV = os.path.join(DATA_DIR, "train.csv")
VALID_CSV = os.path.join(DATA_DIR, "valid.csv")
TEST_CSV = os.path.join(DATA_DIR, "test.csv")

CHECKPOINT_DIR = "checkpoints"
VOCAB_PATH = os.path.join(CHECKPOINT_DIR, "vocabs.pkl")
BEST_MODEL_PATH = os.path.join(CHECKPOINT_DIR, "fdhn_best.pt")
os.makedirs(CHECKPOINT_DIR, exist_ok=True)

# ---------------------------------------------------------------------------
# Dataset / label settings
# ---------------------------------------------------------------------------
NUM_CLASSES = 6
LABEL_NAMES = ["pants-fire", "false", "barely-true", "half-true", "mostly-true", "true"]

# Actual LIAR2 CSV column names for the six credibility-history features
# (f9 - f14 in the paper's Table 2). Note: the paper's text calls f12
# 'barely_true_counts', but the actual released CSV column is 'mostly_false_counts'.
NUMERICAL_COLUMNS = [
    "true_counts", "mostly_true_counts", "half_true_counts",
    "mostly_false_counts", "false_counts", "pants_on_fire_counts",
]

# Textual context columns (f2, f3, f4, f6, f7, f15) - concatenated into one string
CONTEXT_COLUMNS = ["date", "subject", "speaker", "speaker_description", "state_info", "context"]

STATEMENT_COLUMN = "statement"
JUSTIFICATION_COLUMN = "justification"
LABEL_COLUMN = "label"

# ---------------------------------------------------------------------------
# Tokenization / sequence lengths
# ---------------------------------------------------------------------------
MAX_STATEMENT_LEN = 40        # avg statement length is ~17.7 tokens (Table 1)
MAX_CONTEXT_LEN = 60
MAX_JUSTIFICATION_LEN = 120   # avg justification length is ~94.4 tokens (Table 1)
MIN_WORD_FREQ = 2             # words appearing fewer times than this become <UNK>

PAD_TOKEN, PAD_IDX = "<PAD>", 0
UNK_TOKEN, UNK_IDX = "<UNK>", 1

# ---------------------------------------------------------------------------
# Model hyperparameters (Section V-A)
# ---------------------------------------------------------------------------
EMBED_DIM = 128
KERNEL_SIZES = (3, 4, 5)
NUM_FILTERS = 128
DROPOUT = 0.5

NUMERICAL_FEATURE_DIM = 64    # hidden size the 6 raw numerical features get projected to
CNN_OUT_CHANNELS = 32         # CNNBiLSTM's CNN layer output channels, kernel_size=1
LSTM_HIDDEN = 64              # per-direction hidden size; Bi-LSTM -> 128-dim output

USE_JUSTIFICATION = True      # Section V-D: LIAR2 experiments add a 5th TextCNN branch

# ---------------------------------------------------------------------------
# Training hyperparameters
# ---------------------------------------------------------------------------
BATCH_SIZE = 64
LEARNING_RATE = 1e-3
NUM_EPOCHS = 10               # paper: "all model training phases completed within 10 epochs"
SEED = 42


In [4]:
def simple_tokenize(text):
    """Lowercase, keep only alphanumerics, split on whitespace."""
    if not isinstance(text, str):
        return []
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    return text.split()


def build_vocab(token_lists, min_freq=MIN_WORD_FREQ):
    counter = Counter()
    for tokens in token_lists:
        counter.update(tokens)
    vocab = {PAD_TOKEN: PAD_IDX, UNK_TOKEN: UNK_IDX}
    for word, freq in counter.items():
        if freq >= min_freq:
            vocab[word] = len(vocab)
    return vocab


def encode_tokens(tokens, vocab, max_len):
    ids = [vocab.get(t, UNK_IDX) for t in tokens[:max_len]]
    if len(ids) < max_len:
        ids = ids + [PAD_IDX] * (max_len - len(ids))
    return ids


def build_context_text(row):
    parts = []
    for col in CONTEXT_COLUMNS:
        val = row.get(col, "")
        if pd.notna(val):
            parts.append(str(val))
    return " ".join(parts)


def fit_vocabs_and_scaler(train_df):
    """Fit everything on the TRAINING split only, to avoid leakage."""
    statement_tokens = [simple_tokenize(s) for s in train_df[STATEMENT_COLUMN]]
    context_tokens = [simple_tokenize(build_context_text(row)) for _, row in train_df.iterrows()]
    justification_tokens = [
        simple_tokenize(s) for s in train_df.get(JUSTIFICATION_COLUMN, pd.Series([""] * len(train_df)))
    ]

    statement_vocab = build_vocab(statement_tokens)
    context_vocab = build_vocab(context_tokens)
    justification_vocab = build_vocab(justification_tokens)

    numerical = train_df[NUMERICAL_COLUMNS].fillna(0).astype(float).values
    mean = numerical.mean(axis=0)
    std = numerical.std(axis=0)
    std[std == 0] = 1.0

    return {
        "statement_vocab": statement_vocab,
        "context_vocab": context_vocab,
        "justification_vocab": justification_vocab,
        "numerical_mean": mean,
        "numerical_std": std,
    }


def encode_row(row, vocabs):
    """Encode a single dataframe row into model-ready arrays."""
    statement_ids = encode_tokens(simple_tokenize(row[STATEMENT_COLUMN]), vocabs["statement_vocab"], MAX_STATEMENT_LEN)
    context_ids = encode_tokens(simple_tokenize(build_context_text(row)), vocabs["context_vocab"], MAX_CONTEXT_LEN)
    justification_ids = encode_tokens(
        simple_tokenize(row.get(JUSTIFICATION_COLUMN, "")), vocabs["justification_vocab"], MAX_JUSTIFICATION_LEN
    )

    raw_numerical = np.array([float(row.get(c, 0) or 0) for c in NUMERICAL_COLUMNS], dtype=np.float32)
    numerical = (raw_numerical - vocabs["numerical_mean"]) / vocabs["numerical_std"]

    label = int(row[LABEL_COLUMN])

    return {
        "statement": np.array(statement_ids, dtype=np.int64),
        "context": np.array(context_ids, dtype=np.int64),
        "justification": np.array(justification_ids, dtype=np.int64),
        "numerical": numerical.astype(np.float32),
        "label": label,
    }

In [5]:
print(f"Loading training data from {TRAIN_CSV} ...")
train_df = pd.read_csv(TRAIN_CSV)
print(f"  {len(train_df)} rows")

print("Fitting vocabularies and scaler on training split ...")
vocabs = fit_vocabs_and_scaler(train_df)
print(f"  statement vocab size:     {len(vocabs['statement_vocab'])}")
print(f"  context vocab size:       {len(vocabs['context_vocab'])}")
print(f"  justification vocab size: {len(vocabs['justification_vocab'])}")

with open(VOCAB_PATH, "wb") as f:
    pickle.dump(vocabs, f)
print(f"Saved vocabularies to {VOCAB_PATH}")

Loading training data from liar2/train.csv ...
  18369 rows
Fitting vocabularies and scaler on training split ...
  statement vocab size:     10046
  context vocab size:       8226
  justification vocab size: 21756
Saved vocabularies to checkpoints/vocabs.pkl


In [6]:
from torch.utils.data import Dataset, DataLoader

class LiarDataset(Dataset):
    def __init__(self, csv_path, vocabs):
        self.df = pd.read_csv(csv_path)
        self.vocabs = vocabs

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        encoded = encode_row(row, self.vocabs)
        return {
            "statement": torch.tensor(encoded["statement"], dtype=torch.long),
            "context": torch.tensor(encoded["context"], dtype=torch.long),
            "justification": torch.tensor(encoded["justification"], dtype=torch.long),
            "numerical": torch.tensor(encoded["numerical"], dtype=torch.float32),
            "label": torch.tensor(encoded["label"], dtype=torch.long),
        }


train_ds = LiarDataset(TRAIN_CSV, vocabs)
valid_ds = LiarDataset(VALID_CSV, vocabs)
test_ds = LiarDataset(TEST_CSV, vocabs)


In [7]:
from torch.utils.data import Dataset, DataLoader

class LiarDataset(Dataset):
    def __init__(self, csv_path, vocabs):
        self.df = pd.read_csv(csv_path)
        self.vocabs = vocabs

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        encoded = encode_row(row, self.vocabs)
        return {
            "statement": torch.tensor(encoded["statement"], dtype=torch.long),
            "context": torch.tensor(encoded["context"], dtype=torch.long),
            "justification": torch.tensor(encoded["justification"], dtype=torch.long),
            "numerical": torch.tensor(encoded["numerical"], dtype=torch.float32),
            "label": torch.tensor(encoded["label"], dtype=torch.long),
        }


train_ds = LiarDataset(TRAIN_CSV, vocabs)
valid_ds = LiarDataset(VALID_CSV, vocabs)
test_ds = LiarDataset(TEST_CSV, vocabs)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=0)
valid_loader = DataLoader(valid_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)
test_loader = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

print(f"Train batches: {len(train_loader)} | Valid batches: {len(valid_loader)} | Test batches: {len(test_loader)}")

Train batches: 288 | Valid batches: 36 | Test batches: 36


In [8]:
class TextCNN(nn.Module):
    """Section IV-A / IV-B: TextCNN with 3 parallel conv kernel sizes + max-pool."""

    def __init__(self, vocab_size, embed_dim, kernel_sizes, num_filters, output_dim, dropout):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=PAD_IDX)
        self.convs = nn.ModuleList(
            [nn.Conv1d(embed_dim, num_filters, kernel_size=k) for k in kernel_sizes]
        )
        self.dropout = nn.Dropout(dropout)
        self.fc = nn.Linear(num_filters * len(kernel_sizes), output_dim)

    def forward(self, x):
        # x: (batch, seq_len)
        emb = self.embedding(x).permute(0, 2, 1)  # (batch, embed_dim, seq_len)
        pooled_outputs = []
        for conv in self.convs:
            c = F.relu(conv(emb))                                   # (batch, num_filters, L-k+1)
            p = F.max_pool1d(c, kernel_size=c.size(2)).squeeze(2)    # (batch, num_filters)
            pooled_outputs.append(p)
        cat = torch.cat(pooled_outputs, dim=1)
        cat = self.dropout(cat)
        return self.fc(cat)                                          # (batch, output_dim)


class CNNBiLSTM(nn.Module):
    """Section IV-C: linear+dropout -> CNN(out=32, kernel=1) -> Bi-LSTM -> linear.

    Returns both the final projected output (for the Fuse Layer) and the
    pooled Bi-LSTM hidden representation (fed to the Fuzzy Layer per IV-D).
    """

    def __init__(self, num_numerical_features, feature_dim, cnn_out_channels, lstm_hidden, output_dim, dropout):
        super().__init__()
        self.input_linear = nn.Linear(num_numerical_features, feature_dim)
        self.dropout1 = nn.Dropout(dropout)
        self.cnn = nn.Conv1d(in_channels=1, out_channels=cnn_out_channels, kernel_size=1)
        self.lstm = nn.LSTM(
            input_size=cnn_out_channels, hidden_size=lstm_hidden,
            num_layers=1, batch_first=True, bidirectional=True,
        )
        self.dropout2 = nn.Dropout(dropout)
        self.output_linear = nn.Linear(lstm_hidden * 2, output_dim)
        self.hidden_dim = lstm_hidden * 2  # exposed for the Fuzzy Layer's feature_dim

    def forward(self, x):
        # x: (batch, num_numerical_features)
        h = self.input_linear(x)            # (batch, feature_dim)
        h = self.dropout1(h)
        h = h.unsqueeze(1)                  # (batch, 1, feature_dim) -> 1 'channel'
        h = F.relu(self.cnn(h))             # (batch, cnn_out_channels, feature_dim)
        h = h.permute(0, 2, 1)              # (batch, feature_dim, cnn_out_channels) -> seq for LSTM
        lstm_out, _ = self.lstm(h)          # (batch, feature_dim, lstm_hidden*2)
        pooled = lstm_out[:, -1, :]         # last timestep -> (batch, lstm_hidden*2)
        pooled = self.dropout2(pooled)
        out = self.output_linear(pooled)    # (batch, output_dim)
        return out, pooled


class FuzzyLayer(nn.Module):
    """Section IV-D: Gaussian-membership Fuzzy Layer (Eq. 1 and Eq. 2).

    For each class j and feature k, computes a Gaussian membership degree
    mu_G(x_k; m_jk, sigma_jk), then averages over features (a t-norm-like
    operation) to get mu_ij, the membership of instance i to class j.
    """

    def __init__(self, feature_dim, num_classes):
        super().__init__()
        self.feature_dim = feature_dim
        self.num_classes = num_classes
        self.centers = nn.Parameter(torch.randn(num_classes, feature_dim) * 0.1)      # m_jk
        self.log_sigmas = nn.Parameter(torch.zeros(num_classes, feature_dim))          # sigma_jk (softplus'd)

    def forward(self, x):
        # x: (batch, feature_dim)
        sigmas = F.softplus(self.log_sigmas) + 1e-3            # always > 0
        x = x.unsqueeze(1)                                     # (batch, 1, feature_dim)
        centers = self.centers.unsqueeze(0)                    # (1, num_classes, feature_dim)
        sigmas = sigmas.unsqueeze(0)                            # (1, num_classes, feature_dim)
        membership = torch.exp(-0.5 * ((x - centers) / sigmas) ** 2)  # Eq. 1
        mu = membership.mean(dim=2)                             # Eq. 2, (batch, num_classes)
        return mu


class FDHN(nn.Module):
    """Full Fuzzy Deep Hybrid Network (Fig. 1)."""

    def __init__(self, statement_vocab_size, context_vocab_size,
                 justification_vocab_size=None, use_justification=USE_JUSTIFICATION):
        super().__init__()
        self.use_justification = use_justification and justification_vocab_size is not None

        self.news_text_module = TextCNN(
            statement_vocab_size, EMBED_DIM, KERNEL_SIZES, NUM_FILTERS, NUM_CLASSES, DROPOUT
        )
        self.textual_context_module = TextCNN(
            context_vocab_size, EMBED_DIM, KERNEL_SIZES, NUM_FILTERS, NUM_CLASSES, DROPOUT
        )
        self.numerical_context_module = CNNBiLSTM(
            num_numerical_features=len(NUMERICAL_COLUMNS),
            feature_dim=NUMERICAL_FEATURE_DIM,
            cnn_out_channels=CNN_OUT_CHANNELS,
            lstm_hidden=LSTM_HIDDEN,
            output_dim=NUM_CLASSES,
            dropout=DROPOUT,
        )
        self.fuzzy_layer = FuzzyLayer(
            feature_dim=self.numerical_context_module.hidden_dim, num_classes=NUM_CLASSES
        )

        num_branches = 4
        if self.use_justification:
            self.justification_module = TextCNN(
                justification_vocab_size, EMBED_DIM, KERNEL_SIZES, NUM_FILTERS, NUM_CLASSES, DROPOUT
            )
            num_branches = 5

        self.fuse_layer = nn.Linear(NUM_CLASSES * num_branches, NUM_CLASSES)

    def forward(self, statement, context, numerical, justification=None):
        out1 = self.news_text_module(statement)                     # Output 1
        out2 = self.textual_context_module(context)                 # Output 2
        out3, numerical_hidden = self.numerical_context_module(numerical)  # Output 3
        out4 = self.fuzzy_layer(numerical_hidden)                   # Output 4

        outputs = [out1, out2, out3, out4]

        if self.use_justification:
            assert justification is not None, "justification tensor required when use_justification=True"
            out5 = self.justification_module(justification)         # Output 5 (LIAR2 extension)
            outputs.append(out5)

        fused = torch.cat(outputs, dim=1)                            # Fuse Layer input
        logits = self.fuse_layer(fused)
        return logits

In [9]:
model = FDHN(
    statement_vocab_size=len(vocabs["statement_vocab"]),
    context_vocab_size=len(vocabs["context_vocab"]),
    justification_vocab_size=len(vocabs["justification_vocab"]),
    use_justification=USE_JUSTIFICATION,
).to(DEVICE)

num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Trainable parameters: {num_params:,}")
model

Trainable parameters: 5,774,674


FDHN(
  (news_text_module): TextCNN(
    (embedding): Embedding(10046, 128, padding_idx=0)
    (convs): ModuleList(
      (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,))
      (1): Conv1d(128, 128, kernel_size=(4,), stride=(1,))
      (2): Conv1d(128, 128, kernel_size=(5,), stride=(1,))
    )
    (dropout): Dropout(p=0.5, inplace=False)
    (fc): Linear(in_features=384, out_features=6, bias=True)
  )
  (textual_context_module): TextCNN(
    (embedding): Embedding(8226, 128, padding_idx=0)
    (convs): ModuleList(
      (0): Conv1d(128, 128, kernel_size=(3,), stride=(1,))
      (1): Conv1d(128, 128, kernel_size=(4,), stride=(1,))
      (2): Conv1d(128, 128, kernel_size=(5,), stride=(1,))
    )
    (dropout): Dropout(p=0.5, inplace=False)
    (fc): Linear(in_features=384, out_features=6, bias=True)
  )
  (numerical_context_module): CNNBiLSTM(
    (input_linear): Linear(in_features=6, out_features=64, bias=True)
    (dropout1): Dropout(p=0.5, inplace=False)
    (cnn): Conv1d(1, 32, k

In [10]:
def run_epoch(model, loader, criterion, optimizer=None, device=DEVICE):
    is_train = optimizer is not None
    model.train() if is_train else model.eval()

    total_loss = 0.0
    all_preds, all_labels = [], []

    context_manager = torch.enable_grad() if is_train else torch.no_grad()
    with context_manager:
        for batch in tqdm(loader, leave=False):
            statement = batch["statement"].to(device)
            context = batch["context"].to(device)
            justification = batch["justification"].to(device)
            numerical = batch["numerical"].to(device)
            labels = batch["label"].to(device)

            if is_train:
                optimizer.zero_grad()

            logits = model(statement, context, numerical, justification)
            loss = criterion(logits, labels)

            if is_train:
                loss.backward()
                optimizer.step()

            total_loss += loss.item() * labels.size(0)
            preds = logits.argmax(dim=1).detach().cpu().numpy()
            all_preds.extend(preds)
            all_labels.extend(labels.detach().cpu().numpy())

    avg_loss = total_loss / len(loader.dataset)
    accuracy = accuracy_score(all_labels, all_preds)
    f1_macro = f1_score(all_labels, all_preds, average="macro")
    f1_micro = f1_score(all_labels, all_preds, average="micro")
    return avg_loss, accuracy, f1_macro, f1_micro

In [11]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=LEARNING_RATE)

best_val_acc = 0.0
for epoch in range(1, NUM_EPOCHS + 1):
    start = time.time()
    train_loss, train_acc, train_f1_macro, train_f1_micro = run_epoch(model, train_loader, criterion, optimizer)
    val_loss, val_acc, val_f1_macro, val_f1_micro = run_epoch(model, valid_loader, criterion, optimizer=None)
    elapsed = time.time() - start

    print(
        f"Epoch {epoch:2d}/{NUM_EPOCHS} | {elapsed:5.1f}s | "
        f"train_loss={train_loss:.4f} acc={train_acc:.4f} f1m={train_f1_macro:.4f} | "
        f"val_loss={val_loss:.4f} acc={val_acc:.4f} f1_macro={val_f1_macro:.4f} f1_micro={val_f1_micro:.4f}"
    )

    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), BEST_MODEL_PATH)
        print(f"  -> new best model saved (val_acc={val_acc:.4f})")

Epoch  1/10 |  79.2s | train_loss=1.4488 acc=0.4020 f1m=0.3569 | val_loss=1.2759 acc=0.4802 f1_macro=0.4571 f1_micro=0.4802
  -> new best model saved (val_acc=0.4802)


Epoch  2/10 |  83.2s | train_loss=1.2245 acc=0.5045 f1m=0.4783 | val_loss=1.1966 acc=0.5098 f1_macro=0.4683 f1_micro=0.5098
  -> new best model saved (val_acc=0.5098)


Epoch  3/10 |  85.9s | train_loss=1.1152 acc=0.5548 f1m=0.5362 | val_loss=1.1575 acc=0.5307 f1_macro=0.4981 f1_micro=0.5307
  -> new best model saved (val_acc=0.5307)


Epoch  4/10 |  91.3s | train_loss=1.0152 acc=0.5996 f1m=0.5861 | val_loss=1.1359 acc=0.5494 f1_macro=0.5238 f1_micro=0.5494
  -> new best model saved (val_acc=0.5494)


Epoch  5/10 |  95.5s | train_loss=0.8900 acc=0.6545 f1m=0.6464 | val_loss=1.2499 acc=0.5255 f1_macro=0.5029 f1_micro=0.5255


Epoch  6/10 |  95.3s | train_loss=0.7966 acc=0.6937 f1m=0.6862 | val_loss=1.1926 acc=0.5364 f1_macro=0.5131 f1_micro=0.5364


Epoch  7/10 |  93.4s | train_loss=0.6586 acc=0.7511 f1m=0.7452 | val_loss=1.3176 acc=0.5407 f1_macro=0.5130 f1_micro=0.5407


Epoch  8/10 |  91.2s | train_loss=0.5939 acc=0.7768 f1m=0.7746 | val_loss=1.3291 acc=0.5263 f1_macro=0.4985 f1_micro=0.5263


Epoch  9/10 |  91.4s | train_loss=0.4556 acc=0.8321 f1m=0.8284 | val_loss=1.3921 acc=0.5163 f1_macro=0.5093 f1_micro=0.5163


Epoch 10/10 | 102.7s | train_loss=0.3653 acc=0.8654 f1m=0.8630 | val_loss=1.4895 acc=0.5250 f1_macro=0.5108 f1_micro=0.5250


In [12]:
print("Evaluating best model on the TEST set ...")
model.load_state_dict(torch.load(BEST_MODEL_PATH, map_location=DEVICE))
test_loss, test_acc, test_f1_macro, test_f1_micro = run_epoch(model, test_loader, criterion, optimizer=None)

print(f"TEST  loss={test_loss:.4f} accuracy={test_acc:.4f} f1_macro={test_f1_macro:.4f} f1_micro={test_f1_micro:.4f}")
print()
print("Paper's reference numbers (Table 6, TC+TC+CB+FZ, LIAR):")
print("  test accuracy=0.465  f1_macro=0.470  f1_micro=0.465")
print("Paper's reference numbers (Table 7, full LIAR2 'LIAR+NEW Mix'):")
print("  test accuracy=0.702  f1_macro=0.696  f1_micro=0.702")

Evaluating best model on the TEST set ...


TEST  loss=1.1167 accuracy=0.5475 f1_macro=0.5191 f1_micro=0.5475

Paper's reference numbers (Table 6, TC+TC+CB+FZ, LIAR):
  test accuracy=0.465  f1_macro=0.470  f1_micro=0.465
Paper's reference numbers (Table 7, full LIAR2 'LIAR+NEW Mix'):
  test accuracy=0.702  f1_macro=0.696  f1_micro=0.702


In [13]:
model.eval()
all_preds, all_labels = [], []
with torch.no_grad():
    for batch in test_loader:
        statement = batch["statement"].to(DEVICE)
        context = batch["context"].to(DEVICE)
        justification = batch["justification"].to(DEVICE)
        numerical = batch["numerical"].to(DEVICE)
        labels = batch["label"].to(DEVICE)

        logits = model(statement, context, numerical, justification)
        preds = logits.argmax(dim=1).cpu().numpy()

        all_preds.extend(preds)
        all_labels.extend(labels.cpu().numpy())

print("Classification report:\n")
print(classification_report(all_labels, all_preds, target_names=LABEL_NAMES, digits=3))

print("Confusion matrix (rows=true, cols=predicted):")
print(confusion_matrix(all_labels, all_preds))

Classification report:

              precision    recall  f1-score   support

  pants-fire      0.677     0.353     0.464       303
       false      0.530     0.783     0.632       660
 barely-true      0.602     0.425     0.498       360
   half-true      0.483     0.577     0.526       371
 mostly-true      0.720     0.344     0.465       343
        true      0.492     0.571     0.529       259

    accuracy                          0.547      2296
   macro avg      0.584     0.509     0.519      2296
weighted avg      0.577     0.547     0.535      2296

Confusion matrix (rows=true, cols=predicted):
[[107 171  12   6   0   7]
 [ 37 517  34  36   4  32]
 [  6 107 153  73   6  15]
 [  4  68  28 214  23  34]
 [  3  53  17  87 118  65]
 [  1  60  10  27  13 148]]


In [14]:
import torch.nn.functional as F

def predict_statement(statement, speaker="", subject="", speaker_description="",
                       state_info="national", context="", date="",
                       true_counts=0, mostly_true_counts=0, half_true_counts=0,
                       mostly_false_counts=0, false_counts=0, pants_on_fire_counts=0,
                       justification=""):
    row = {
        "statement": statement, "date": date, "subject": subject, "speaker": speaker,
        "speaker_description": speaker_description, "state_info": state_info, "context": context,
        "true_counts": true_counts, "mostly_true_counts": mostly_true_counts,
        "half_true_counts": half_true_counts, "mostly_false_counts": mostly_false_counts,
        "false_counts": false_counts, "pants_on_fire_counts": pants_on_fire_counts,
        "justification": justification, "label": 0,  # placeholder, unused at inference time
    }
    encoded = encode_row(row, vocabs)
    statement_t = torch.tensor(encoded["statement"]).unsqueeze(0).to(DEVICE)
    context_t = torch.tensor(encoded["context"]).unsqueeze(0).to(DEVICE)
    justification_t = torch.tensor(encoded["justification"]).unsqueeze(0).to(DEVICE)
    numerical_t = torch.tensor(encoded["numerical"]).unsqueeze(0).to(DEVICE)

    model.eval()
    with torch.no_grad():
        logits = model(statement_t, context_t, numerical_t, justification_t)
        probs = F.softmax(logits, dim=1).squeeze(0).cpu().numpy()

    predicted_idx = probs.argmax()
    print(f"Predicted: {LABEL_NAMES[predicted_idx]}  (confidence: {probs[predicted_idx]:.1%})\n")
    for name, p in sorted(zip(LABEL_NAMES, probs), key=lambda x: -x[1]):
        print(f"  {name:>12s}: {p:.1%}")

# Example call:
predict_statement(
    statement="The unemployment rate has fallen to its lowest level in fifty years.",
    speaker="a-politician", subject="economy,jobs",
    speaker_description="A senator who has served three terms.",
    context="a televised debate",
)

Predicted: true  (confidence: 45.9%)

          true: 45.9%
         false: 15.5%
   mostly-true: 14.2%
     half-true: 11.0%
    pants-fire: 7.5%
   barely-true: 6.0%


In [ ]:
# Additional prediction examples
examples = [
    {
        "name": "Goodyear political hats claim",
        "statement": "Goodyear Tires announced a ban on all political hats at their factories.",
        "speaker": "a-commentator",
        "subject": "politics,workplace",
        "context": "a social media post",
    },
    {
        "name": "Unemployment claim",
        "statement": "The unemployment rate has fallen to its lowest level in fifty years.",
        "speaker": "a-politician",
        "subject": "economy,jobs",
        "context": "a televised debate",
    },
    {
        "name": "Chocolate and memory claim",
        "statement": "Daily chocolate consumption improves memory.",
        "subject": "health,science",
        "context": "an online article",
    },
]

for example in examples:
    print(f"\n{'=' * 60}\n{example['name']}\n{'=' * 60}")
    prediction_input = {key: value for key, value in example.items() if key != "name"}
    predict_statement(**prediction_input)

In [ ]:
# Quick custom prediction
predict_statement(
    statement="Goodyear Tires announced a ban on all political hats at their factories.",
    speaker="a-commentator",
    subject="politics,workplace",
    context="a social media post",
)